services:
  rocm1:
    # just for cosmetics
    hostname: rocm1

    build:
      context: g4ad_rocm_build
    volumes:
      - .:/workspace:ro
    working_dir: /workspace
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/kfd
      - /dev/dri
    group_add: [video]
    ipc: host
    # network_mode: host
    shm_size: 8gb

  cuda1:
    # just for cosmetics
    hostname: cuda1

    build:
      context: g4dn_cuda_build
    volumes:
      - .:/workspace:ro
    working_dir: /workspace
    ipc: host
    # network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]